/*
 * Lighthouse
 * © 2026 ayushshrivastv
 */

import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import SessionSetter from '@/src/lib/SessionSeter';
import { authOption } from '@/app/api/auth/[...nextauth]/options';
import ShortcutMenu from '@/src/components/utility/ShortcutMenuModal';
import { headers } from 'next/headers';

interface Props {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: 'BlackIn',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Props) {
    const headerStore = await headers();
    const host = headerStore.get('host') ?? '';
    const hostname = host.split(':')[0];
    const isLocalHost =
        hostname === 'localhost' ||
        hostname === '127.0.0.1' ||
        hostname === '::1' ||
        hostname.endsWith('.local');
    const skipAuth =
        process.env.NODE_ENV !== 'production' ||
        process.env.NEXT_PUBLIC_SKIP_AUTH === 'true' ||
        isLocalHost;
    const session = skipAuth ? null : await getServerSession(authOption);

    return (
        <div className="flex h-screen w-screen items-center justify-center bg-black">
            {children}
            <ShortcutMenu />
            <SessionSetter session={session} />
        </div>
    );
}
